name: doctoolchain-ci

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug workspace (safe)
        run: |
          echo "PWD: $(pwd)"
          ls -R docs || true
          find . -name index.adoc || true

      - name: Run doctoolchain-action
        uses: ./
        with:
          dtcw-path: "./dtcw"
          config-file: "docToolchainConfig.groovy"
          output-path: "build/docs"
      - name: Upload docs
        uses: actions/upload-artifact@v4
        with:
          name: doctoolchain-docs
          path: build/docs