name: CI test doctoolchain-action

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: pwd
      - run: ls -la
      - name: Debug filesystem
        run: |
          pwd
          ls -R
          find / -name docToolchainConfig.groovy 2>/dev/null || true
      - name: Run doctoolchain-action (local path)
        uses: ./
        #with:
          # hier deine echten Inputs aus action.yml eintragen
          # output-path: ""
          # tasks: ""
          # config-file: ""
          # dtcw-path: ""