name: CI test doctoolchain-action

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Debug filesystem
        run: |
          pwd
          ls -la
          ls -R
      - name: Run doctoolchain-action (local path)
        uses: ./
        with:
          # hier deine echten Inputs aus action.yml eintragen
          # output-path: ""
          # tasks: ""
          config-file: "project/docToolchainConfig.groovy"
          # dtcw-path: ""